CREATE TABLE IF NOT EXISTS student
(
   id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name varchar(100) NOT NULL,
   age int NOT NULL,
   name_kana varchar(100) NOT NULL,
   nickname varchar(100) DEFAULT NULL,
   email varchar(255) NOT NULL,
   gender varchar(10) NOT NULL,
   place_of_residence varchar(255) DEFAULT NULL,
   remark varchar(255) DEFAULT NULL,
   is_deleted boolean
);

CREATE TABLE IF NOT EXISTS student_course
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name varchar(100) NOT NULL,
    start_date date NOT NULL,
    end_date date DEFAULT NULL,
    student_id int NOT NULL
);

CREATE TABLE IF NOT EXISTS student_course_status
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id int NOT NULL,
    status varchar(50) NOT NULL DEFAULT 'TEMPORARY_APPLICATION'
);
